# Generated by Django 3.1 on 2021-03-29 22:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('slug', models.SlugField(blank=True, verbose_name='shortcut')),
                ('img', models.ImageField(blank=True, upload_to='projects_images')),
                ('efforts', models.DurationField()),
                ('status', models.CharField(choices=[('elaboração', 'Elaboração'), ('execução', 'Execução'), ('concluíndo', 'Concluído')], default='elaboração', max_length=40)),
                ('time_course', models.CharField(choices=[('1', 'No prazo'), ('2', 'Atrasado'), ('3', 'Concluído')], default=1, max_length=7)),
                ('dead_line', models.DateField()),
                ('complete_per', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assign', models.ManyToManyField(related_name='projects_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projeto',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('data_conclusao', models.DateTimeField(null=True)),
                ('horario_de_inicio_atual', models.DateTimeField(auto_now_add=True, null=True)),
                ('duracao_total', models.DurationField(default=datetime.timedelta(0), null=True)),
                ('status', models.CharField(choices=[(0, 'ABERTA'), (1, 'TRABALHANDO'), (2, 'PAUSADA'), (3, 'CONCLUíDA')], default=0, max_length=19)),
                ('complete_per', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pre_requisito', models.ManyToManyField(default=0, related_name='pre_requisitos', to='projects.Tarefa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projects.project')),
            ],
            options={
                'db_table': 'tarefa',
            },
        ),
    ]
